name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: debian:11
    steps:
      - run: apt update && apt install sudo
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1.2.5
      - name: Run MATLAB Command
        uses: matlab-actions/run-command@v1.2.2
        with:
          command: disp('hello')
          
