name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - run: apt update && apt install sudo curl unzip -y
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
      - name: Run MATLAB Command
        uses: matlab-actions/run-command@v1.2.2
        with:
          command: disp('hello')
          
